name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24.x'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install compactc
      run: |
        sudo mkdir -p /opt/compact
        wget https://github.com/LFDT-Minokawa/compact/releases/download/compactc-v0.31.1/compactc_v0.31.1_x86_64-unknown-linux-musl.zip
        sudo unzip compactc_v0.31.1_x86_64-unknown-linux-musl.zip -d /opt/compact
        sudo chmod +x /opt/compact/*
        echo "/opt/compact" >> $GITHUB_PATH

    - name: Install Dependencies
      run: npm ci
      working-directory: .

    - name: Compile Compact Contract
      run: npm run compact
      working-directory: ./contract

    - name: Build Next.js Application
      run: npm run build
      working-directory: ./frontend
      env:
        NEXT_PUBLIC_NETWORK_ID: preview
        NEXT_PUBLIC_INDEXER_URL: https://indexer.preview.midnight.network/api/v4/graphql
        NEXT_PUBLIC_INDEXER_WS_URL: wss://indexer.preview.midnight.network/api/v4/graphql/ws
        NEXT_PUBLIC_NODE_URL: https://rpc.preview.midnight.network
        NEXT_PUBLIC_PROOF_SERVER_URL: http://127.0.0.1:6300

    - name: Start Proof Server
      run: docker run -d -p 6300:6300 midnightntwrk/proof-server:8.0.3

    - name: Run On-Chain E2E Tests
      run: npx tsx scripts/e2e-test.ts
      working-directory: .
      env:
        NEXT_PUBLIC_CONTRACT_ADDRESS: fd1b841ba4dff397916eb0ca339574f1f4e276edc8e02ab44459f6951ff638fa
        PREVIEW_TEST_WALLET_KEY: ${{ secrets.PREVIEW_TEST_WALLET_KEY }}

    - name: Run Linting
      run: npm run lint
      working-directory: ./frontend
      continue-on-error: true # Known misconfiguration in the starter template for this specific step
